spring:
  application.name: "code-challenge"
server:
  port: ${APP_PORT:8080}

  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"
    listener:
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      uri: "mongodb://mongo:27017/mongodatabase"
game:
  player:
    name: ${PLAYER_NAME:player1}