spring:
  application.name: "code-challenge"

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: "consumer-group"
      auto-offset-reset: earliest
    bootstrap-servers: "localhost:9092"

  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"

  data:
    mongodb:
      uri: "mongodb://localhost:27017/mongodatabase"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2database
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  #    http://localhost:8080/h2-console
  h2.console.enabled: true